#!/usr/bin/env python3
"""Collects the Luna pictures the installer skin (lunaskin.cpp) draws with: frame and caption pieces from prebuilt/Luna,
buttons / check boxes / radio buttons / progress from luna.msstyles. Writes assets/*.png and skin.rc (run from the repo root)."""
import sys
from pathlib import Path
from PIL import Image
sys.path.insert(0, "tools")
import import_msstyles as m

out = Path("tools/installer_skin/assets"); out.mkdir(parents=True, exist_ok=True)
pre = Path("prebuilt/Luna")
names = []
def put(name, image):
    image.convert("RGBA").save(out / f"{name}.png"); names.append(name)

for n in ("title-left", "title-fill", "title-right", "title-left-inactive", "title-fill-inactive", "title-right-inactive",
          "frame-left", "frame-right", "bottom-left", "bottom-fill", "bottom-right",
          "caption-normal", "caption-hover", "caption-pressed", "close-normal", "close-hover", "close-pressed",
          "close-glyph-normal", "close-glyph-hover", "close-glyph-pressed",
          "minimize-glyph-normal", "minimize-glyph-hover", "minimize-glyph-pressed",
          "progress-track", "progress-chunk"):
    put(n.replace("-", "_"), Image.open(pre / f"{n}.png"))

images = m.bitmaps(Path("themes/luna/Luna/luna.msstyles"))
def sheet(suffix):
    return m.find(images, suffix, "BLUE")
button = sheet("_BUTTON_BMP")           # normal, hot, pressed, disabled, default (23 px each)
def clean_button(state):
    state = state.convert("RGBA")
    px = state.load()
    for y in range(state.height):
        for x in range(state.width):
            r, g, b, _ = px[x, y]
            if (r, g, b) == (154, 133, 106) or (y == state.height - 1 and (r, g, b) == (255, 255, 255)):
                px[x, y] = (r, g, b, 0)   # the picture's key colour and its separator row
    return state
for i, s in enumerate(("normal", "hot", "pressed", "disabled", "default")):
    put(f"button_{s}", clean_button(m.button_state(button, i)))
check = sheet("_CHECKBOX13_BMP")        # 13 px each: unchecked normal/hot/pressed/disabled, checked ..., mixed ...
radio = sheet("_RADIOBUTTON13_BMP")     # unchecked normal/hot/pressed/disabled, checked ...
for kind, strip in (("check", check), ("radio", radio)):
    for i, s in enumerate(("normal", "hot", "pressed", "disabled")):
        put(f"{kind}_off_{s}", m.strip_state(strip, 13, i))
        put(f"{kind}_on_{s}", m.strip_state(strip, 13, i + 4))
icon = Image.open("build/icon.png").convert("RGBA").resize((16, 16), Image.LANCZOS)
put("icon16", icon)
put("fail_side", Image.open("tools/installer_skin/fail_side.png"))   # the picture of a failed setup (tools/installer_art.py)

with open("tools/installer_skin/skin.rc", "w") as rc:
    for i, n in enumerate(names, 1):
        rc.write(f'{i} RCDATA "assets/{n}.png"\n')
with open("tools/installer_skin/skin_ids.h", "w") as h:
    h.write("// generated by make_assets.py\n")
    for i, n in enumerate(names, 1):
        h.write(f"#define IMG_{n.upper()} {i}\n")
    h.write(f"#define IMG_COUNT {len(names)}\n")
print(len(names), "pictures")
