const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('windowControls', {
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  setWindowMeta: (title, icon) => ipcRenderer.send('window:set-meta', { title, icon }),
  openThemeSettings: tab => ipcRenderer.send('theme:open-settings', typeof tab === 'string' ? tab : undefined),
  openControlPanel: () => ipcRenderer.send('control-panel:open'),
  openHelpViewer: spec => ipcRenderer.send('help-viewer:open', typeof spec === 'string' ? spec : ''),
  openAddon: (id, query) => ipcRenderer.invoke('addon:open', String(id || ''), query && typeof query === 'object' ? Object.fromEntries(Object.entries(query).map(([key, value]) => [key, String(value)])) : {}),
  openAbout: appName => ipcRenderer.send('about:open', String(appName || 'nekochat')),
  openHelp: topic => ipcRenderer.send('help:open', typeof topic === 'string' ? topic : undefined),
  openGame: options => ipcRenderer.send('game:open', { level: String(options?.level || ''), seed: String(options?.seed || ''), chat: String(options?.chat || '') }),
  openApplet: (applet, tab) => ipcRenderer.send('applet:open', String(applet || ''), typeof tab === 'string' ? tab : undefined),
  openThemeBrowser: () => ipcRenderer.send('theme:open-browser'),
  openThemeEditor: () => ipcRenderer.send('theme:open-editor'),
  loadThemeForEditor: (id, scheme) => ipcRenderer.invoke('theme-editor:load', id, scheme),
  saveEditedTheme: theme => ipcRenderer.invoke('theme-editor:save', theme),
  openEmojiBrowser: () => ipcRenderer.send('emoji:open-browser'),
  openProfileSettings: () => ipcRenderer.send('profile:open-settings'),
  openRoomCreate: () => ipcRenderer.send('room:create-open'),
  openCallWindow: state => ipcRenderer.send('call:open', state),
  updateCallWindow: state => ipcRenderer.send('call:update', state),
  closeCallWindow: () => ipcRenderer.send('call:close'),
  callAction: action => ipcRenderer.send('call:action', action),
  detachChat: chat => ipcRenderer.invoke('chat:detach', chat),
  returnChat: chat => ipcRenderer.send('chat:return', chat),
  closeDetachedChats: () => ipcRenderer.send('chat:close-all'),
  focusDetachedChat: chat => ipcRenderer.invoke('chat:focus-detached', chat),
  listThemes: () => ipcRenderer.invoke('theme:list'),
  getActiveTheme: () => ipcRenderer.invoke('theme:current'),
  previewTheme: (id, scheme) => ipcRenderer.invoke('theme:preview', id, scheme),
  applyTheme: (id, scheme) => ipcRenderer.invoke('theme:apply', id, scheme),
  importTheme: () => ipcRenderer.invoke('theme:import'),
  exportThemeFiles: () => ipcRenderer.invoke('backup:export-themes'),
  restoreThemeFiles: archive => ipcRenderer.invoke('backup:restore-themes', archive),
  relaunch: () => ipcRenderer.send('app:relaunch'),
  getUpdateInfo: () => ipcRenderer.invoke('update:info'),
  installUpdate: (release, options) => ipcRenderer.invoke('update:install', release, options),
  restartToUpdate: () => ipcRenderer.send('update:restart'),
  onUpdateStatus: callback => ipcRenderer.on('update:status', (_, status) => callback(status)),
  listCatalogThemes: () => ipcRenderer.invoke('theme:browser-list'),
  getCatalogThemeDetails: id => ipcRenderer.invoke('theme:browser-details', id),
  installCatalogTheme: id => ipcRenderer.invoke('theme:browser-install', id),
  listCatalogPacks: () => ipcRenderer.invoke('pack:catalog'),
  getCatalogPackDetails: id => ipcRenderer.invoke('pack:details', String(id || '')),
  installCatalogPack: id => ipcRenderer.invoke('pack:install', id),
  openInstallWindow: items => ipcRenderer.invoke('install:open', items),
  getInstallJob: () => ipcRenderer.invoke('install:job'),
  finishInstall: summary => ipcRenderer.send('install:finish', summary),
  getCatalogPackSize: id => ipcRenderer.invoke('pack:size', String(id || '')),
  cancelPackInstall: id => ipcRenderer.invoke('pack:cancel', String(id || '')),
  onPackProgress: callback => { const listener = (_, data) => callback(data); ipcRenderer.on('pack:progress', listener); return () => ipcRenderer.removeListener('pack:progress', listener); },
  listPacks: () => ipcRenderer.invoke('pack:list'),
  removePack: id => ipcRenderer.invoke('pack:remove', id),
  removeTheme: id => ipcRenderer.invoke('theme:remove', id),
  notifyMessage: message => ipcRenderer.send('notification:message', message),
  setUnreadCount: count => ipcRenderer.send('unread:set', count),
  // Desktop only: the server admin panel (the renderer cannot send its session cookie).
  openAdminPanel: server => ipcRenderer.send('admin:open', server),
  adminRequest: request => ipcRenderer.invoke('admin:request', request),
  onBalloonShow: callback => ipcRenderer.on('balloon:show', (_, data) => callback(data)),
  balloonClick: () => ipcRenderer.send('balloon:click'),
  balloonClose: () => ipcRenderer.send('balloon:close'),
  showSystemDialog: data => ipcRenderer.send('system:show', data),
  systemAction: action => ipcRenderer.send('system:action', action),
  getDisplaySettings: () => ipcRenderer.invoke('display:current'),
  prepareDisplayCapture: () => ipcRenderer.invoke('display:prepare-capture'),
  applyDisplaySettings: settings => ipcRenderer.invoke('display:apply', settings),
  // Only the desktop app can choose the DNS resolver; phone WebViews use the system one.
  dnsSupported: true,
  onThemeChanged: callback => ipcRenderer.on('theme:changed', (_, data) => callback(data)),
  onSettingsTab: callback => ipcRenderer.on('settings:show-tab', (_, tab) => callback(tab)),
  onHelpTopic: callback => ipcRenderer.on('help:topic', (_, topic) => callback(topic)),
  onDisplayChanged: callback => ipcRenderer.on('display:changed', (_, data) => callback(data)),
  onProfileChanged: callback => ipcRenderer.on('profile:changed', (_, data) => callback(data)),
  onRoomCreated: callback => ipcRenderer.on('room:created', (_, data) => callback(data)),
  onCallUpdate: callback => ipcRenderer.on('call:update', (_, data) => callback(data)),
  onCallAction: callback => ipcRenderer.on('call:action', (_, data) => callback(data)),
  onChatRestore: callback => ipcRenderer.on('chat:restore', (_, data) => callback(data)),
  onEmojiSelected: callback => ipcRenderer.on('emoji:selected', (_, emoji) => callback(emoji)),
  onSystemDialog: callback => ipcRenderer.on('system:update', (_, data) => callback(data)),
  onSystemAction: callback => ipcRenderer.on('system:action', (_, action) => callback(action)),
  selectEmoji: emoji => ipcRenderer.send('emoji:selected', emoji),
  profileChanged: user => ipcRenderer.send('profile:changed', user),
  roomCreated: room => ipcRenderer.send('room:created', room),
  resize: (direction, dx, dy) => ipcRenderer.send('window:resize', { direction, dx, dy })
});
// The window frame uses the inactive half of the theme's frame images while the window is not focused.
ipcRenderer.on('window:focus', (_, focused) => document.documentElement.classList.toggle('xp-inactive', !focused));
